firstproject/accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name='accounts'

urlpatterns=[
    url(r'^$',views.login_view,name="login"),
    url(r'logout/$',views.logout_view,name="logout"),
]

firstproject/firstproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from letsdoit import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',views.home,name='home'),
    url(r'^index/',views.index,name='index'),
    url(r'^testing/',views.testing,name='testing'),
# url(r'logout/$',views.logout_view,name="logout"),
    url(r'^(?P<year>[\f\w-]+)/$',views.subjects,name='subjects'),
    url(r'^files/(?P<categorie>[\f\w-]+)/$',views.files,name='files'),
    url(r'',include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

firstproject/accounts/models.py
from django.db import models

# Create your models here.

firstproject/letsdoit/models.py
from django.db import models


class clasyear(models.Model):
    choice=[('2nd-year','2'),('3rd-year','3'),('4th-year','4')]
    year=models.CharField(choices=choice,max_length=100)
    name=models.CharField(max_length=30,unique=True)
    description=models.CharField(max_length=50,blank=True)
    def __str__(self):
        return self.name

 
class filest(models.Model):
    fname=models.FileField()
    def get_absolute_url(self):
        return reverse('files:detail',kwargs={'pk':self.pk})
    fdescription=models.CharField(max_length=50,blank=True)
    usn=models.CharField(max_length=50)

    categorie = models.ForeignKey(clasyear,to_field='name',
    on_delete=models.CASCADE,
    )     
   
class a(models.Model):
    aa=models.CharField(max_length=20,blank=True)

class files(models.Model):
    filename=models.FileField()  
    def get_absolute_url(self):
        return reverse('files:detail',kwargs={'pk':self.pk})  
    fdescription=models.CharField(max_length=50,blank=True)
    categorie = models.CharField(max_length=50,blank=True)
       
# class classyear(models.Model):
#     year=models.CharField(max_length=5)
# class subjects(models.Model):
#     choice=[('1','Second year'),('2','Thrird year'),('3','Fourth year')]
#     year=models.CharField(choices=choice,max_length=1)
#     name=models.CharField(max_length=20)
#     description=models.CharField(max_length=50,blank=True)


# class livings(models.Model):
#     type=[('a','animals'),('b','birds')]
#     types=models.CharField(choices=type,max_length=1,blank=True)
#     name=models.CharField(max_length=20)
#     age=models.IntegerField()
#     legs=models.IntegerField()

# class Myinfo(models.Model):
#     SEX=[('f','female'),('m','male')]
#     name=models.CharField(max_length=100)
#     age= models.CharField(max_length=100)
#     gender= models.CharField(choices=SEX,max_length=1,blank=True)
#     submission=models.DateField()
#     myjob=models.ManyToManyField('Myjob',blank=True)
# class title(models.Model):
#     job=models.CharField(max_length=50)
#     exp=models.IntegerField() 
# class child(models.Model):
#     age=models.IntegerField()
#     name=models.CharField(max_length=20)    
# class Myjob(models.Model):
#     name=models.CharField(max_length=50)    
    
#     def __str__(self):
#         return self.name

 

firstproject/letsdoit/forms.py
from django import forms


from .models import filest    

from .models import clasyear
class PostForm(forms.ModelForm):
    class Meta:   
        fdescription = forms.CharField(max_length=2000,
        widget=forms.Textarea() )
        model = filest
        fields = ('fname','fdescription','usn' ,'categorie',)
        widgets = {'categorie': forms.HiddenInput(),'usn': forms.HiddenInput()}
        

firstproject/accounts/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def login_view(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)  
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            return redirect('/home/')

    else:
        form=AuthenticationForm() 
    return render(request,'login.html',{'form':form})
def logout_view(request):
    if request.method=='POST':
        logout(request) 
        return redirect('/')   

firstproject/letsdoit/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from django.http import HttpResponse,HttpResponseRedirect
from .models import clasyear
from .models import filest
from .forms import PostForm


def home(request):
    yea=clasyear.objects.order_by('year').values('year').distinct()
    if request.user.is_authenticated:    
        return render(request,'home.html',{'yea':yea,})
    else:
        return redirect("/")

def index(request):
    return render(request,'index.html')

def testing(request):
    return render(request,'testing.html')    


def details(request,name):
    detail=clasyear.objects.filter(name=name)

    contentValue = {'detail':detail}
    if request.user.is_authenticated:    
        return render(request,'details.html',contentValue)
    else:
        return redirect("/")


def subjects(request,year):
    subject=clasyear.objects.filter(year=year)
    if request.user.is_authenticated:    
        return render(request,'subjects.html',{'subject':subject})   
    else:
        return redirect("/")

def files(request,categorie):
    print(categorie)
    usn = None
    if request.user.is_authenticated:
        usn = request.user.username
    file=filest.objects.filter(categorie=categorie).order_by('fname')
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
           
    else:
        form = PostForm( initial = {'categorie':categorie,'usn':usn})
    if request.user.is_authenticated:    
        return render(request,'files.html',{'file':file,'form':form})   
    else:
        return redirect("/")


  

firstproject/accounts/templates/index.html
<html>
    <head>

        <link rel="Stylesheet" href="style.css" >
    </head>
    <body>

        <div id="particles-js">
  
        </div>
<script src="particle.js"></script>

<script>
    particlesJS.load('particles-js',
    'package.json',function(){
       

    });
</script>


    </body>
</html>

firstproject/accounts/templates/login.html
<html>
    
    
    
    
    
    
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>

    /*
 * Specific styles of signin component
 */
/*
 * General styles
 */
body, html {
    height: 100%;
    background-repeat: no-repeat;
    background-image: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));
}

.card-container.card {
    max-width: 350px;
    padding: 40px 40px;
}

.btn {
    font-weight: 700;
    height: 36px;
    -moz-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

/*
 * Card component
 */
.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}

/*
 * Form styles
 */
.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.reauth-email {
    display: block;
    color: #404040;
    line-height: 2;
    margin-bottom: 10px;
    font-size: 14px;
    text-align: center;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 0px;
    font-weight: 700;
    font-size: 14px;
    height: 36px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color: rgb(12, 97, 33);
}


</style>    
<body>

<div class="container ">
        <div class="card card-container">
        <center> <h3>ISE file manager</h3></center>   <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            <form class="site-form form-signin" action="/" method="post">
                {% csrf_token %}

            
                {% if next %}
                <input type="hidden" name="next" value="{{ next }}" />
            {% endif %}
                <span id="reauth-email" class="reauth-email"></span>
                <input type="text"name="username" id="inputEmail" class="form-control" placeholder="Username" required autofocus>
                <input type="password"name="password" id="inputPassword" class="form-control" placeholder="Password" required>
               
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
            </form><!-- /form -->
           
        </div><!-- /card-container -->
    </div><!-- /container -->
    </body></html>
 

firstproject/letsdoit/templates/details.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="container">
    <br>

    {% for sub in detail %}  
    <div class="panel panel-default">
          <div class="panel-body">
      <h3>{{sub.name }}</h3>
      <a href="{% url 'files' categorie=sub.name %}"><h3>{{sub.name }}</h3></a>
      <h3>{{sub.year}}</h3>
      <p>{{sub.description}}</p>

        </div></div>
      {% endfor %}
    
    
</div>

firstproject/letsdoit/templates/files.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <style>
           body{
            font-family: 'Roboto', sans-serif;
           } 
           textarea {
                width: 100%;
                padding: 8px;
                border: 1px solid #D1D5DA;
                border-radius: 1px;
                resize: vertical;
                margin-top:3px;
                margin-bottom:3px;
            }
        </style>
    </head>
    <body style="background:#FFFFFF">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="#">hello, ziyazee</a>
                  </li> 
                </ul>
                <form action="accounts/logout/"method="post" style="margin:0">
                    {% csrf_token %}

                   <button type="submit"class="btn"><span>logout</span></button>
                </form>
        </nav>

        <div class="container">    
   <br>             <center> <h2>{{request.resolver_match.kwargs.categorie}}</h2></center>
                <div style="border:1px solid #D1D5DA;padding:10px;border-radius:5px;background-color:#FFFFFF"><center><h4>New post</h4></center>
                    <div style="">
                        <form method="POST" class="post-form"enctype="multipart/form-data">
                             {% csrf_token %}

                            <div class="custom-file">
                                    <input id="logo" type="file" name="fname"class="custom-file-input">
                                    <label for="logo" class="custom-file-label">Choose file...</label>
                                 </div>
                                 <script>$('.custom-file-input').on('change', function() { 
                                        let fileName = $(this).val().split('\\').pop(); 
                                        $(this).next('.custom-file-label').addClass("selected").html(fileName); 
                                     });</script>
                        
                            <div class="form-group">
                                <textarea class="form-control"name="fdescription"placeholder="write description here..." id="exampleFormControlTextarea1" rows="2"></textarea>
                            </div>
                            <input type="hidden" name="usn"id="id_usn" value= {{ user.get_username }}  />
                            <input type="hidden" name="categorie" id="id_categorie"  value= {{request.resolver_match.kwargs.categorie}} />
                            <center> 
                                <button type="submit" class="btn btn-success"style="width:100%;"><span style="">Save</span></button>
                            </center>
                        </form>
                    </div>
                </div>
            <div class="row">
                {% for sub in file %} 
                <div class="col-sm-6 ">
                    <div class="card" style="background-color: #FFFFFF;margin-top:5px;">
                        <div class="card-body">
                            <h5 class="card-title" style="color:#586069">{{ sub.fname }}</h5>
                            <p class="card-text" style="color:#586069">{{sub.fdescription }}</p>
                            <a href="{{ sub.fname.url }}"download class="card-link">Download</a>
                            <span class="card-link" style="font-size: 11px;color:#586069">contributed by {{ sub.usn }}</span>
                        </div>
                    </div>
                </div>
                {% endfor %} 
            </div>
            <br>
        </div>
    </body>
</html>
    <!-- <div class="card-group row">

            {% for sub in file %} 
            <div class="card col-sm-6" style="background-color: #FFFFFF;margin-top:5px;">
                    <div class="card-block">
                      <h4 class="card-title" style="color:#586069">{{ sub.fname }}</h4>
                      <p class="card-text" style="color:#586069">{{sub.fdescription }}</p>
                      <a href="{{ sub.fname.url }}"download class="card-link">Download</a>
                      <span class="card-link" style="font-size: 11px;color:#586069">contributed by {{ sub.usn }}</span>
                    </div>
                  
              </div>
        
                {% endfor %}  -->

firstproject/letsdoit/templates/home.html
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<body style="background:#FFFFFF">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
           
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">hello, ziyazee</a>
              </li> 
            </ul>
           
    </nav>
    <div class="container" >
        <br>
    <div class="row">
            <div class="col-sm-9">
        <div class="jumbotron">
          <h3>Information Science and engineering</h3>      
          <p>Get your important notes,files here...</p>
        </div>
          
   


    {% for y in yea %}
    <div class="card" ><div class="card-body">
            <div class="card-title"> 
    <a href="{% url 'subjects' year=y.year %}" style="text-decoration:none;">
            
    <b>{{ y.year }}</b>
    </a>
    
    </div></div></div>
    <br>
    {% endfor %} 

</div>
<!-- <div class="col-sm-3" >
    <br><center> <img src="../media/default-user.png">
    <h1><span style="color:white">{{ user.get_username }}</span></h1>
</center> -->
<!-- <div style="width:100%;height:45%;background-color:aqua;overflow:auto">
       
</div>

<h4><span style="color:white">feedback:</span></h4><input type="text"style="width:100%"><br>
<center><input type="button" value="button"></center> -->
</div></div>

</body>

firstproject/letsdoit/templates/index.html
<h1>hye</h1>

<h2>{{ user.get_username }}</h2>
<a href="/">hye</a>

firstproject/letsdoit/templates/subjects.html
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<body style="background:#FFFFFF">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
               
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="#">hello, ziyazee</a>
                  </li> 
                </ul>
                <form action="accounts/logout/"method="post" style="margin:0">
                    {% csrf_token %}
    
                   <button type="submit"class="btn"><span>logout</span></button>
                </form>
        </nav>

<div class="container">
    <br>
    
<div class="jumbotron">
    <h1>Subjects</h1>
</div>
      {% for sub in subject %}  
     
            <div class="card" >
                <div class="card-body">
<div class="card-title">          
     <a href="{% url 'files' categorie=sub.name %}" style="text-decoration:none;"><b>{{sub.name }}</b></a>
</div>
                    <div class="card-subtitle mb-2 text-muted">{{sub.description}}</div>
          </div></div>
          <br>
        {% endfor %}
    
</div>


</body>

firstproject/letsdoit/templates/testing.html
<h1>working</h1><h2>{{ user.get_username }}</h2>